team: sprcom
pipeline: fs2-pdf
slack_channel: '#sprcom-janitors'
triggers:
  - type: git
    branch: maven
tasks:
- type: docker-compose
  name: test
  compose_file: ops/docker-compose.yml
  service: build
  command: ops/test.bash
- type: docker-compose
  manual_trigger: true
  name: publish
  compose_file: ops/docker-compose.yml
  service: build
  command: ops/publish.bash
  vars:
    artifactory_username: sprcom-artifactory
    artifactory_password: ((sprcom-artifactory.authtoken))
    github_ssh_key: ((sprcom-artifactory.sshkey))
    sf_ci_gpg_main: ((sf-ci-gpg-main.key))
    sf_ci_sonatype_password: ((sf-ci-sonatype.password))
feature_toggles:
- update-pipeline
