name: scala-steward
on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2am UTC
  workflow_dispatch:

env:
  VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
  VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
  ARTIFACTORY_PASSWORD: ${{ secrets.EE_ARTIFACTORY_PASSWORD }}
  ARTIFACTORY_URL: ${{ secrets.EE_ARTIFACTORY_URL }}
  ARTIFACTORY_USERNAME: ${{ secrets.EE_ARTIFACTORY_USERNAME }}

jobs:
  scala-steward:
    runs-on: ee-runner
    container: eu.gcr.io/halfpipe-io/build-openjdk11-scala
    name: Launch Scala Steward
    timeout-minutes: 60
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          author-email: ecommerce-dev@springernature.com
          author-name: Scala Steward
      - name: 'Notify slack #ecommerce-ops (failure)'
        if: failure()
        uses: yukin01/slack-bot-action@v0.0.4
        with:
          status: ${{ job.status }}
          oauth_token: ${{ secrets.EE_SLACK_TOKEN }}
          channel: '#ecommerce-ops'
          text: ':redsiren: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.repository }} // ${{ github.workflow }} / ${{ github.run_number }}> failed'
